backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images
collections:
  - name: "peliculas"
    label: "Peliculas"
    folder: "content/peliculas"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "pelicula_{{hour}}{{minute}}{{second}}"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Nationality", name: "nationality", widget: "string"}
      - {label: "Launch_year", name: "launch_year", widget: "number"}
      - {label: "times", name: "fields", widget: "select", multiple: true,
         options: ["80's", "90's"]}
      - {label: "Image", name: "image", widget: "image",
           media_folder: '/static/images/peliculas'}
      - {label: "Body", name: "body", widget: "markdown"}
  # - name: "publishers"
  #   label: "Publishers"
  #   folder: "content/publishers"
  #   create: true
  #   fields:
  #     - {label: "Id", name: "id", widget: "hidden", default: "publisher_{{hour}}{{minute}}{{second}}"}
  #     - {label: "Name", name: "name", widget: "string"}
  #     - {label: "Country", name: "country", widget: "string"}
  #     - {label: "Founded", name: "founded", widget: "number"}
  #     - {label: "Genere", name: "genere", widget: "select", multiple: true,
  #        options: ["Academic", "Education", " Computer Science"]}
  #     - {label: "Image", name: "image", widget: "image",
  #          media_folder: '/static/images/publishers'}
  #     - {label: "Body", name: "body", widget: "markdown"}
  # - name: "books"
  #   label: "Books"
  #   folder: "content/books"
  #   create: true
  #   fields:
  #     - {label: "Id", name: "id", widget: "hidden", default: "book_{{hour}}{{minute}}{{second}}"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Edition", name: "edition", widget: "string"}
  #     - {label: "Copyright", name: "copyright", widget: "number"}
  #     - {label: "Language", name: "language", widget: "string"}
  #     - {label: "Pages", name: "pages", widget: "number"}
  #     - {label: "Author", name: "authorId", widget: "relation",
  #         collection: "authors", search_fields: ["name"], value_field: "id",
  #         display_fields: ["name"]}
  #     - {label: "Publisher", name: "publisherId", widget: "relation",
  #         collection: "publishers", search_fields: ["name"], value_field: "id",
  #         display_fields: ["name"]}
  #     - {label: "Image", name: "image", widget: "image",
  #          media_folder: '/static/images/books'}
  #     - {label: "Body", name: "body", widget: "markdown"}